url: http://www.kodama.gr
title: "> kodama.gr_"
subtitle:
author: Tasos Latsas
#simple_search: http://google.com/search
description:

root: /
# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"
timezone: Europe/Athens
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5
category_dir: categories
markdown: kramdown
social:
  github: tlatsas
  twitter: tlatsas
  linkedin: tasoslatsas

plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - .idea

remote_theme: yous/whiteglass
